export const navData=[
    'Accueil',
    'Blog',
    'Contact',
     'Qui sommes nous'
]

export const dashboardNavs = [
    {
        name: 'Tableau de bord',
        link: '/dashboard',
        icon: 'HomeIcon'
    },
    {
        name: 'Admins',
        link: '/dashboard/admins',
        icon:'UsersIcon'
    },
    {
        name: 'Partenaire',
        link: '/dashboard/partners',
        icon: 'UserGroupIcon'
    },
    {
        name: 'Étudiants',
        link: '/dashboard/students',
        icon: 'AcademicCapIcon'
    },
    {
        name: 'Admissions',
        link: '/dashboard/admissions',
        icon: 'DocumentIcon'
    },
    {
        name: 'Formations',
        link: '/dashboard/training',
        icon:'ClipboardDocumentListIcon'
    },
    {
        name: 'Niveaux',
        link: '/dashboard/levels',
        icon:'QueueListIcon'
    }
];

export const admissionSteps = [
    {
      title: "Inscription",
      description: "Créez un compte en ligne pour commencer votre processus de candidature.",
      icon: "solar:user-id-broken", // Iconify: Account Plus Outline
    },
    {
      title: "Évaluation et entretien",
      description: "Votre dossier sera évalué et, si accepté, un entretien sera organisé à distance.",
      icon: "solar:document-broken", // Iconify: Clipboard Text Outline
    },
    {
      title: "Modalités de séjour",
      description: "Informations détaillées sur l’obtention du visa étudiant et les modalités de séjour en France.",
      icon: "ion:earth-outline", // Iconify: Earth Outline
    },
    {
      title: "Préparation à l’arrivée",
      description: "Sessions d’orientation pour faciliter l’intégration des étudiants internationaux.",
      icon: "cil:school", // Iconify: School Outline
    },
    {
      title: "Inscription officielle",
      description: "Une fois toutes les démarches complétées, vous serez officiellement inscrit à Scholia.",
      icon: "hugeicons:passport-valid", // Iconify: Check Circle Outline
    },
  ];

  export const signupSteps=[
    {
        id:1,
        title:'Catégorie'
    },
    {
        id:2,
        title:'Informations'
    },
    {
        id:3,
        title:'Compte'
    },
    
  ]

 export const countries = [
  { label: "Afghanistan", key: "af" },
  { label: "Afrique du Sud", key: "za" },
  { label: "Albanie", key: "al" },
  { label: "Algérie", key: "dz" },
  { label: "Allemagne", key: "de" },
  { label: "Andorre", key: "ad" },
  { label: "Angola", key: "ao" },
  { label: "Antigua-et-Barbuda", key: "ag" },
  { label: "Arabie saoudite", key: "sa" },
  { label: "Argentine", key: "ar" },
  { label: "Arménie", key: "am" },
  { label: "Australie", key: "au" },
  { label: "Autriche", key: "at" },
  { label: "Azerbaïdjan", key: "az" },
  { label: "Bahamas", key: "bs" },
  { label: "Bahreïn", key: "bh" },
  { label: "Bangladesh", key: "bd" },
  { label: "Barbade", key: "bb" },
  { label: "Belgique", key: "be" },
  { label: "Belize", key: "bz" },
  { label: "Bénin", key: "bj" },
  { label: "Bhoutan", key: "bt" },
  { label: "Biélorussie", key: "by" },
  { label: "Birmanie (Myanmar)", key: "mm" },
  { label: "Bolivie", key: "bo" },
  { label: "Bosnie-Herzégovine", key: "ba" },
  { label: "Botswana", key: "bw" },
  { label: "Brésil", key: "br" },
  { label: "Brunei", key: "bn" },
  { label: "Bulgarie", key: "bg" },
  { label: "Burkina Faso", key: "bf" },
  { label: "Burundi", key: "bi" },
  { label: "Cambodge", key: "kh" },
  { label: "Cameroun", key: "cm" },
  { label: "Canada", key: "ca" },
  { label: "Cap-Vert", key: "cv" },
  { label: "Chili", key: "cl" },
  { label: "Chine", key: "cn" },
  { label: "Chypre", key: "cy" },
  { label: "Colombie", key: "co" },
  { label: "Comores", key: "km" },
  { label: "Corée du Nord", key: "kp" },
  { label: "Corée du Sud", key: "kr" },
  { label: "Costa Rica", key: "cr" },
  { label: "Côte d’Ivoire", key: "ci" },
  { label: "Croatie", key: "hr" },
  { label: "Cuba", key: "cu" },
  { label: "Danemark", key: "dk" },
  { label: "Djibouti", key: "dj" },
  { label: "Dominique", key: "dm" },
  { label: "Égypte", key: "eg" },
  { label: "Émirats arabes unis", key: "ae" },
  { label: "Équateur", key: "ec" },
  { label: "Érythrée", key: "er" },
  { label: "Espagne", key: "es" },
  { label: "Estonie", key: "ee" },
  { label: "Eswatini", key: "sz" },
  { label: "États-Unis", key: "us" },
  { label: "Éthiopie", key: "et" },
  { label: "Fidji", key: "fj" },
  { label: "Finlande", key: "fi" },
  { label: "France", key: "fr" },
  { label: "Gabon", key: "ga" },
  { label: "Gambie", key: "gm" },
  { label: "Géorgie", key: "ge" },
  { label: "Ghana", key: "gh" },
  { label: "Grèce", key: "gr" },
  { label: "Grenade", key: "gd" },
  { label: "Guatemala", key: "gt" },
  { label: "Guinée", key: "gn" },
  { label: "Guinée-Bissau", key: "gw" },
  { label: "Guinée équatoriale", key: "gq" },
  { label: "Guyana", key: "gy" },
  { label: "Haïti", key: "ht" },
  { label: "Honduras", key: "hn" },
  { label: "Hongrie", key: "hu" },
  { label: "Inde", key: "in" },
  { label: "Indonésie", key: "id" },
  { label: "Irak", key: "iq" },
  { label: "Iran", key: "ir" },
  { label: "Irlande", key: "ie" },
  { label: "Islande", key: "is" },
  { label: "Israël", key: "il" },
  { label: "Italie", key: "it" },
  { label: "Jamaïque", key: "jm" },
  { label: "Japon", key: "jp" },
  { label: "Jordanie", key: "jo" },
  { label: "Kazakhstan", key: "kz" },
  { label: "Kenya", key: "ke" },
  { label: "Kirghizistan", key: "kg" },
  { label: "Kiribati", key: "ki" },
  { label: "Kosovo", key: "xk" },
  { label: "Koweït", key: "kw" },
  { label: "Laos", key: "la" },
  { label: "Lesotho", key: "ls" },
  { label: "Lettonie", key: "lv" },
  { label: "Liban", key: "lb" },
  { label: "Libéria", key: "lr" },
  { label: "Libye", key: "ly" },
  { label: "Liechtenstein", key: "li" },
  { label: "Lituanie", key: "lt" },
  { label: "Luxembourg", key: "lu" },
  { label: "Macédoine du Nord", key: "mk" },
  { label: "Madagascar", key: "mg" },
  { label: "Malaisie", key: "my" },
  { label: "Malawi", key: "mw" },
  { label: "Maldives", key: "mv" },
  { label: "Mali", key: "ml" },
  { label: "Malte", key: "mt" },
  { label: "Maroc", key: "ma" },
  { label: "Marshall", key: "mh" },
  { label: "Maurice", key: "mu" },
  { label: "Mauritanie", key: "mr" },
  { label: "Mexique", key: "mx" },
  { label: "Micronésie", key: "fm" },
  { label: "Moldavie", key: "md" },
  { label: "Monaco", key: "mc" },
  { label: "Mongolie", key: "mn" },
  { label: "Monténégro", key: "me" },
  { label: "Mozambique", key: "mz" },
  { label: "Namibie", key: "na" },
  { label: "Nauru", key: "nr" },
  { label: "Népal", key: "np" },
  { label: "Nicaragua", key: "ni" },
  { label: "Niger", key: "ne" },
  { label: "Nigéria", key: "ng" },
  { label: "Norvège", key: "no" },
  { label: "Nouvelle-Zélande", key: "nz" },
  { label: "Oman", key: "om" },
  { label: "Ouganda", key: "ug" },
  { label: "Ouzbékistan", key: "uz" },
  { label: "Pakistan", key: "pk" },
  { label: "Palaos", key: "pw" },
  { label: "Panama", key: "pa" },
  { label: "Papouasie-Nouvelle-Guinée", key: "pg" },
  { label: "Paraguay", key: "py" },
  { label: "Pays-Bas", key: "nl" },
  { label: "Pérou", key: "pe" },
  { label: "Philippines", key: "ph" },
  { label: "Pologne", key: "pl" },
  { label: "Portugal", key: "pt" },
  { label: "Qatar", key: "qa" },
  { label: "République centrafricaine", key: "cf" },
  { label: "République démocratique du Congo", key: "cd" },
  { label: "République dominicaine", key: "do" },
  { label: "République du Congo", key: "cg" },
  { label: "République tchèque", key: "cz" },
  { label: "Roumanie", key: "ro" },
  { label: "Royaume-Uni", key: "gb" },
  { label: "Russie", key: "ru" },
  { label: "Rwanda", key: "rw" },
  { label: "Saint-Kitts-et-Nevis", key: "kn" },
  { label: "Saint-Marin", key: "sm" },
  { label: "Saint-Vincent-et-les-Grenadines", key: "vc" },
  { label: "Sainte-Lucie", key: "lc" },
  { label: "Salvador", key: "sv" },
  { label: "Samoa", key: "ws" },
  { label: "Sao Tomé-et-Principe", key: "st" },
  { label: "Sénégal", key: "sn" },
  { label: "Serbie", key: "rs" },
  { label: "Seychelles", key: "sc" },
  { label: "Sierra Leone", key: "sl" },
  { label: "Singapour", key: "sg" },
  { label: "Slovaquie", key: "sk" },
  { label: "Slovénie", key: "si" },
  { label: "Somalie", key: "so" },
  { label: "Soudan", key: "sd" },
  { label: "Soudan du Sud", key: "ss" },
  { label: "Sri Lanka", key: "lk" },
  { label: "Suède", key: "se" },
  { label: "Suisse", key: "ch" },
  { label: "Suriname", key: "sr" },
  { label: "Syrie", key: "sy" },
  { label: "Tadjikistan", key: "tj" },
  { label: "Tanzanie", key: "tz" },
  { label: "Tchad", key: "td" },
  { label: "Thaïlande", key: "th" },
  { label: "Timor-Leste", key: "tl" },
  { label: "Togo", key: "tg" },
  { label: "Tonga", key: "to" },
  { label: "Trinité-et-Tobago", key: "tt" },
  { label: "Tunisie", key: "tn" },
  { label: "Turkménistan", key: "tm" },
  { label: "Turquie", key: "tr" },
  { label: "Tuvalu", key: "tv" },
  { label: "Ukraine", key: "ua" },
  { label: "Uruguay", key: "uy" },
  { label: "Vanuatu", key: "vu" },
  { label: "Vatican", key: "va" },
  { label: "Venezuela", key: "ve" },
  { label: "Viêt Nam", key: "vn" },
  { label: "Yémen", key: "ye" },
  { label: "Zambie", key: "zm" },
  { label: "Zimbabwe", key: "zw" },
];

  
  
 
  